# Simple Redis for LLM caching
version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: seraph-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru

volumes:
  redis_data: