apiVersion: v1
data:
  anthropic-api-key: WU9VUl9BTlRIUk9QSUNfQVBJX0tFWQ==
  gemini-api-key: QUl6YVN5QW5GTnJWcUpVeTMxNkpQXy1rMnB4Y3p1ZkZsREUwbTlnCg==
  openai-api-key: WU9VUl9PUEVOQUlfQVBJX0tFWQ==
  seraph-mitigation-api-key: WU9VUl9TRVJBUEhfTUlUSUdBVElPTl9BUElfS0VZ
  server-api-key: QUl6YVN5QmwzbkYyUTN4SGU3Z1FqblZlb21yckhqRDRWc1JJRlc4
kind: Secret
metadata:
  creationTimestamp: "2025-08-16T00:57:41Z"
  name: seraph-secrets
  namespace: default
  resourceVersion: "198421"
  uid: 4eefa133-6791-42fb-8907-600e5944f018
type: Opaque
