apiVersion: v1
data:
  GITHUB_TOKEN: Z2hwXzhJeUE5ZjBIelhMZWE2NU9ueUM4Vm1TU3lRSEk3YTRJR0trbwo=
kind: Secret
metadata:
  creationTimestamp: "2025-08-16T23:50:27Z"
  name: github-mcp-secret
  namespace: default
  resourceVersion: "116390"
  uid: 37de9fb2-de7c-4469-8349-cb419974a283
type: Opaque
