apiVersion: v1
data:
  GEMINI_API_KEY: WU9VUl9HRU1JTklfQVBJX0tFWQ==
kind: Secret
metadata:
  creationTimestamp: "2025-08-16T03:25:59Z"
  name: seraph-api-key
  namespace: default
  resourceVersion: "15314"
  uid: 7e2ebe1f-db61-4f23-9aff-9ec7cbb59e34
type: Opaque
