{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "seraph.fullname" . }}-reader
  labels:
    {{- include "seraph.labels" . | nindent 4 }}
rules:
# Read-only access to most resources for investigation
- apiGroups: [""]
  resources: 
    - pods
    - services
    - endpoints
    - persistentvolumes
    - persistentvolumeclaims
    - configmaps
    - events
    - namespaces
    - nodes
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
    - deployments
    - replicasets
    - daemonsets
    - statefulsets
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources:
    - jobs
    - cronjobs
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources:
    - ingresses
    - networkpolicies
  verbs: ["get", "list", "watch"]
# Pod logs access
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
# Metrics access
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes"]
  verbs: ["get", "list"]
{{- end }}