apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "seraph.fullname" . }}-config
  labels:
    {{- include "seraph.labels" . | nindent 4 }}
data:
  seraph.config.json: |
    {{- .Values.seraphConfig | toPrettyJson | nindent 4 }}
