{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "seraph.fullname" . }}-redis-secret
  labels:
    {{- include "seraph.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
type: Opaque
data:
  redis-password: {{ .Values.redis.auth.password | b64enc | quote }}
{{- end }}